### ISSUE TITLE
[Meta Issue] Write tests for codebase

### ISSUE THREAD

**Issue by tylerpotts** [MetroStar/ib_manifest_util#1]
## Summary

All functions need tests to ensure they do what we expect and to catch bugs before they get into the main branch.  The tests should cover all known cases and potential bugs.  If new bugs appear, new tests should be written to cover the new bug.

We should generally follow the suggested rules of testing given here:
https://docs.python-guide.org/writing/tests/

This issue covers everything except `cli.py`, which we will work on next.

## Proposed implementation

- This is a meta issue (aka Epic), so a new issue should be opened for each task.  Some tasks are in the list below, but other tasks can be added to this meta issue by editing this description.
- There are data files in the `tests` directory that can be used in the tests.  Do not modify the data files.
- All tests should be in the `tests` directory.
- Each module in the repo will have a test file named `tests_{module name}.py`
- Each test will be a function named `test_{some function}.py`

## Acceptance Criteria

- [ ] All functions and methods (except in `cli.py`) have tests (full coverage)

## Tasks to complete

Tests should be written for each function:
- [x] https://github.com/metrostar/ib_manifest_util/blob/main/ib_manifest_util/update_repository.py#L16 #18 
- [ ] https://github.com/metrostar/ib_manifest_util/blob/main/ib_manifest_util/create_dockerfile.py#L9
- [ ] https://github.com/metrostar/ib_manifest_util/blob/main/ib_manifest_util/create_dockerfile.py#L63
- [ ] https://github.com/metrostar/ib_manifest_util/blob/main/ib_manifest_util/create_hardening_manifest.py#L15
- [x] https://github.com/metrostar/ib_manifest_util/blob/main/ib_manifest_util/download_conda_packages.py#L7 #6
- [x] https://github.com/metrostar/ib_manifest_util/blob/main/ib_manifest_util/util.py#L18 #5
- [x] https://github.com/metrostar/ib_manifest_util/blob/main/ib_manifest_util/util.py#L42 
- [x] https://github.com/metrostar/ib_manifest_util/blob/main/ib_manifest_util/util.py#L68 #16 
- [x] https://github.com/metrostar/ib_manifest_util/blob/main/ib_manifest_util/util.py#L78 #12 
- [x] dump_yaml function #15

**Comment by kcpevey** [comment]
Check [here](https://github.com/MetroStar/ib_manifest_util/actions/runs/3106121477/jobs/5032593176) for coverage

**Comment by kcpevey** [comment]
Check [here](https://github.com/MetroStar/ib_manifest_util/actions/runs/3106121477/jobs/5032593176) for coverage
