### ISSUE TITLE
Make tests for `update_repository`

### ISSUE THREAD

**Issue by ericdatakelly** [MetroStar/ib_manifest_util#18]
## Summary

We need a test for the whole workflow.  

## Proposed implementation

Create a test with a small list of packages and generate files that can be used for comparison for future tests.

## Acceptance Criteria

`update_repository` runs on CI/CD without errors

## Tasks to complete

- [ ] Get files from an existing repo (trim the number of packages to a few small packages, less than 10 kB each)
- [ ] Put the files into a folder with the structure of a repo
- [ ] Generate files using the workflow
- [ ] Save the generated files for comparison with future tests

## Related to

#1

**Comment by kcpevey** [comment]
Resolved by #23
