### ISSUE TITLE
Update cli.py

### ISSUE THREAD

**Issue by tylerpotts** [MetroStar/ib_manifest_util#3]
## Summary

The code was heavily refactored to incorporate jinja templating, but `cli.py` was not updated. 

## Proposed implementation

Walk through `cli.py` and update the code to work with the new codebase.

## Acceptance Criteria

- [ ] `cli.py` runs without errors
- [ ] Tests for `cli.py` pass

## Tasks to complete

- [ ] Update `cli.py` as needed
- [ ] Write tests for `cli.py`
