### ISSUE TITLE
[META] Fill out documentation pages

### ISSUE THREAD

**Issue by kcpevey** [MetroStar/ib_manifest_util#38]
## Summary

Need docs for:
* [x] update repo - python method @kcpevey 
* [x] download packages - python method @kcpevey 
* [ ] cli - available commands and how to use @iameskild 

## Related to

#37 must be merged first
